filebeat.inputs:
# Docker container logları (sanal makine için)
- type: log
  enabled: true
  paths:
    - '/var/lib/docker/containers/*/*.log'
    - '/mnt/data-storage/docker/containers/*/*.log'
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log
  fields:
    log_type: "docker"
  fields_under_root: true

# Sistem logları (Ubuntu)
- type: log
  enabled: true
  paths:
    - /var/log/syslog
    - /var/log/auth.log
    - /var/log/kern.log
    - /var/log/dpkg.log
    - /var/log/apt/history.log
  fields:
    log_type: "system"
  fields_under_root: true

# Application logları
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/*/*.log
  fields:
    log_type: "application"
  fields_under_root: true

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_cloud_metadata: ~
- add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch.emm-cyber.de:443"]
  username: "elastic"
  password: "ElasticPass123!"
  index: "docker-logs-%{+yyyy.MM.dd}"
  
  # HTTPS kullanıyoruz
  protocol: "https"
  ssl.verification_mode: "none"  # Self-signed sertifika için

setup.template.name: "docker-logs"
setup.template.pattern: "docker-logs-*"

setup.kibana:
  host: "kibana.emm-cyber.de:443"
  username: "kibana_user"
  password: "KibanaPass123!"
  
  # HTTPS kullanıyoruz
  protocol: "https"
  ssl.verification_mode: "none"  # Self-signed sertifika için

logging.level: debug
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644 