filebeat.inputs:
# Docker container logları - otomatik olarak tüm container loglarını okur
- type: container
  enabled: true
  paths:
    - '/mnt/data-storage/docker/containers/*/*.log'
  stream: all
  processors:
    - add_docker_metadata: ~
    - decode_json_fields:
        fields: ["log"]
        target: ""
        overwrite_keys: true
        add_error_key: true

# Sistem logları (Ubuntu)
- type: log
  enabled: true
  paths:
    - /var/log/syslog
    - /var/log/auth.log
    - /var/log/kern.log
    - /var/log/dpkg.log
    - /var/log/apt/history.log
  fields:
    log_type: "system"
  fields_under_root: true

# Application logları
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/*/*.log
  fields:
    log_type: "application"
  fields_under_root: true

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_cloud_metadata: ~
- add_fields:
    fields:
      source: "docker_logs"

output.elasticsearch:
  hosts: ["elasticsearch.emm-cyber.de:443"]
  username: "elastic"
  password: "ElasticPass123!"
  index: "docker-logs-%{+yyyy.MM.dd}"
  
  # HTTPS kullanıyoruz
  protocol: "https"
  ssl.verification_mode: "none"  # Self-signed sertifika için

setup.template.name: "docker-logs"
setup.template.pattern: "docker-logs-*"

setup.kibana:
  host: "kibana.emm-cyber.de:443"
  username: "kibana_user"
  password: "KibanaPass123!"
  
  # HTTPS kullanıyoruz
  protocol: "https"
  ssl.verification_mode: "none"  # Self-signed sertifika için

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644 